### ISSUE TITLE
What is the most recommended SLAM package to use on MRS1xxx LiDAR?

### ISSUE THREAD

**Issue by chrisfernam2** [SICKAG/sick_scan#12]
I want to be able to use SLAM to map an area, save the map with the capability of restoring it at anytime, and ultimately tell my robot (which contains encoder-based servo motors ) to drive to a specific location in the map itself. 

I previously tampered with a turtlebot3 and its SLAM capabilities, and i was wondering if there exists a package that best offers these functionalities for the LiDAR.

**Comment by michael1309** [comment]
This is a very interesting question which is often discussed in many respects. As a sensor manufacturer we supply the data for the SLAM algorithms and other tracking and classification systems. We would like to advise you to ask this question in the corresponding ROS forums, as it goes beyond the connection of the SICK scanner to the ROS world. A good starting point can be the page http://wiki.ros.org/AutonomousSLAM 
If you have new experiences here, we are looking forward to your feedback.

**Comment by chrisfernam2** [comment]
I did so yesterday. However, I'm still facing problems getting a general mapping feature to work. I been having trouble with slam_gmapping packages, hector_slam, etc. All i want to do is simply record a map for now, no localization required.

**Comment by michael1309** [comment]
Hi Chris,

We try to support you. Today we started by investigating slam_gmapping in cooperation with MRS6xxx. We will keep you informed. We plan to give you a detailed feedback during the next week.

**Comment by michael1309** [comment]
This was a typo. We will start with the MRS1xxx.

**Comment by chrisfernam2** [comment]
Great! I look forward for the response. Thanks!

**Comment by michael1309** [comment]
It seems like your robot contains wheel encoders. Therefore you could alternatively try gmapping. You can have a look at test_004_mrs1xxx_slam.launch. hector_slam also runs with IMU support. 
May I ask what type of robot you use? Maybe you can send a photo sometime. I'd like that.

**Comment by chrisfernam2** [comment]
The encoder-based servo motors i'm using are Applied Motion's
J0400-305-4-000 60mm Servo Motors
https://www.applied-motion.com/products/servo-motors/j0400-305-4-000


The drive i use to control it via ethernet is the SV2D10 - Q - DE Master
Drive.
https://www.applied-motion.com/products/servo-drives/sv2d10-q-de

The servo has a high resolution incremental encoder, up to 10,000 counts;
that is, count = 0 is the default position, and 9999 is one exact
revolution or 360 degrees.

Also, i ran the launch file, but is it supposed to launch rviz by itself? I
ran rviz in a different terminal but i'm not sure if its mapping. Could you
guide me through the process?

**Comment by michael1309** [comment]
Here are the settings for your rviz (and a small example of slam of my office room with open door).
You can setup rviz by adding a "Map" with topic "/map". That's it.

**Comment by michael1309** [comment]
I also changed the ip address to the default ip address.

Just type:
roslaunch sick_scan test_005_hector.launch
and afterwards start rviz and add a map with topic /map

**Comment by chrisfernam2** [comment]
I tried, but i get warning : "No Map received". Which makes sense since i
see no /map topic when i run the launch file as noted in the picture.  I
also got an error with the slam_gmapping package, also in the pictures
below. I tried fixing this error before but haven't been able to.

**Comment by michael1309** [comment]
Please setup the hector_slam-algorithm in the first step. 
The transformation between odom and map will be produced by the "hector_mapping"-Tools.
That is the trick of SLAM.
The hector_mapping is a separate tool not included in the package.

Try the following steps (or similar):
1. cd <your_workspace>/src
2. git clone https://github.com/tu-darmstadt-ros-pkg/hector_slam/tree/catkin/hector_mapping
3. cd ..
4. catkin_make
DONE

**Comment by chrisfernam2** [comment]
I'm still facing errors. I'd appreciate if you could guide me in more
detail. I entered the commands you instructed me; however,
i am unaware of the concept:

"The transformation between odom and map will be produced by the
"hector_mapping"-Tools.
That is the trick of SLAM.
The hector_mapping is a separate tool not included in the package. "

**Comment by michael1309** [comment]
Now the setup is very ease. I wrote a script for automatic setup, installing, starting and visualization.
Please follow: https://github.com/SICKAG/sick_scan/blob/devel/doc/slam.md#example-setup

**Comment by chrisfernam2** [comment]
i haven't performed the TF tree for my robot yet. However, are you saying i
can perform slam as portrayed in this video:
https://www.youtube.com/watch?v=F8pdObV_df4 by using the laser_scan_matcher?

**Comment by michael1309** [comment]
For this kind of good result you should integrate an IMU (in this video this was a "IMU Analog Combo Board Razor - 6DOF Ultra-Thin IMU").
