### ISSUE TITLE
Hello, I found that the ROS driver will crash during use. What is the reason?

### ISSUE THREAD

**Issue by WangQJuan** [SICKAG/sick_scan#158]
Hello, I found that the ROS driver will crash during use. What is the reason
<img width="655" alt="8c5cbfd2007e36f6a0fef4bb3d0b0dd837080f01c97cb1e2816f3cb3c32b26e0QzpcVXNlcnNcREVMTFxBcHBEYXRhXFJvYW1pbmdcRGluZ1RhbGtcMzE3NTk1Mjg3X3YyXEltYWdlRmlsZXNcMTY0NTQyODI4MTQ4NjM4OTMyMjg0NjBfNTI2MTk3MDI0MzdfOEY1NDE4NkItODg3Mi00NDVmLTk5MjgtNEE0OUFEQUU4N0Q3LnBuZw==" src="https://user-images.githubusercontent.com/52991922/154908326-e3126d39-669d-45e3-8168-bdf0039ba816.png">
?

**Comment by rostest** [comment]
Thanks for reporting! The error seems to have occurred before ("Error acitivating LIDouputstate message"), causing sick_generic_caller to terminate. Please post the complete output from start, or at least the complete error message.

**Comment by WangQJuan** [comment]
Hello, thank you for your support. The following is the error information
![2022-02-21 07-28-19_sickEorr_0](https://user-images.githubusercontent.com/52991922/154933146-c51ba36c-2ad1-4c36-a486-1be681c806c0.png)
![2022-02-21 07-27-13_sickEorr_1](https://user-images.githubusercontent.com/52991922/154933165-a0c51b33-0f19-4a2f-819f-c55a3851406c.png)
![2022-02-21 07-27-35_sickEorr_2](https://user-images.githubusercontent.com/52991922/154933184-d3ef83ba-f335-485e-bcd5-e1b80bbd181a.png)
.

**Comment by rostest** [comment]
Thanks! I'll have a closer look to the error and get back on this as soon as possible. If possible, consider an update to the sick_scan_xd driver on https://github.com/SICKAG/sick_scan_xd with the most recent version.

**Comment by WangQJuan** [comment]
Thank you for your support and wait for your good news.

**Comment by rostest** [comment]
LFErec, LIDinputstate and LIDoutputstate have been activated after switching to measurement mode. Depending on timing, this could lead to mismatching scandata and sopas response messages. The bug is fixed in the latest release 1.12.0 by changing the sopas startup sequence.
Please update the sources and rebuild the driver. Thanks again!

**Comment by gowtham212** [comment]
Hi while I am launching this file sick_scan sick_lms_1xx.launch 
roslaunch sick_scan sick_lms_1xx.launch 
I get code from devel branch https://github.com/SICKAG/sick_scan.git
I got error like this

![Screenshot from 2022-05-05 16-35-00](https://user-images.githubusercontent.com/44162806/166910940-47db67b5-9641-4e64-bca6-a96748276d35.png)

**Comment by rostest** [comment]
Thanks for reporting. Please use the latest release https://github.com/SICKAG/sick_scan/releases/tag/1.12.1 or the master branch. Checkout using `git clone https://github.com/SICKAG/sick_scan.git`
We recommend to switch to https://github.com/SICKAG/sick_scan_xd for the most recent driver version.

**Comment by hasanzfdn** [comment]
ı got same error, tried 1.12.1 release and master branch but still doesn't solved.

**Comment by rostest** [comment]
Thanks for reporting. Please use the repository on https://github.com/SICKAG/sick_scan_xd with the most recent releases.

**Comment by hasanzfdn** [comment]
Thank you for replying. I solved by close the wi-fi and unplug-plug the ethernet cable.

**Comment by rostest** [comment]
Thanks!
